### ISSUE TITLE
Program: MUTO - INTL exceptions

### ISSUE THREAD

**Issue by bhavikbhagat93** [icgc-argo/roadmap#1039]

**Comment by lindaxiang** [comment]
- [x] Specimen: https://github.com/icgc-argo/roadmap/issues/1049
- [x] Primary Diagnosis: https://github.com/icgc-argo/roadmap/issues/1048
- [x] Treatment:
       - [ ] https://github.com/icgc-argo/roadmap/issues/1053
       - [ ] https://github.com/icgc-argo/roadmap/issues/1052
       - [ ] https://github.com/icgc-argo/roadmap/issues/1054
       - [ ] https://github.com/icgc-argo/roadmap/issues/1051
- [x] Missing entity exceptions: https://github.com/icgc-argo/roadmap/issues/1121
