### ISSUE TITLE
Program: P1000-US Exceptions

### ISSUE THREAD

**Issue by bhavikbhagat93** [icgc-argo/roadmap#1045]
Request received on Jan12, 2024

- [ ] Donor level exception for `specimen` schema fields: percent_tumour_cells, percent_tumour_cells_measurement_method.
https://github.com/icgc-argo/roadmap/issues/1044
- [ ] Donor level exception for `treatment` schema fields: https://github.com/icgc-argo/roadmap/issues/1089
       - [ ] treatment_setting: 
       - [ ] treatment_start_interval: interval field exception
       https://github.com/icgc-argo/roadmap/issues/1054
- [ ] Donor level exception for `follow up` schema fields: 
       - [ ] anatomic_site_progression_or_recurrence
       - [ ] interval_of_followup: interval field exception
       https://github.com/icgc-argo/roadmap/issues/1083
