### ISSUE TITLE
GDPR Compliance 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#136]
https://wiki.oicr.on.ca/display/icgcargotech/GDPR+Complicance 

To complete this epic:

- [ ] Edit and Approve Website Privacy Statement 
- [ ] Update the approved text on https://platform-ui.qa.argo.cancercollaboratory.org/privacy 
- [ ] Complete the UI for cookie pop-up notice
