### ISSUE TITLE
IT Setup & Hardware Estimation

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/roadmap#137]
- [x] Infra doc outlining projected production needs for end of Q1 2020 prod launch (@andricDu and @henro001 )
- [x] Delivery of the Openstack tenant by IT to us (@akachru-github ) 
- [x] Confirmation of the final domain that will be used (@christinayung )
> NOTE: prefer icgc-argo.org, will settle for platform or dcc.

Moving out of scope of this Epic into the January release:
- [ ] Plan or EGO failover from OICR to Collab (@henro001 )
- [ ] List of endpoints for healthchecks (@akachru-github)
- [ ] Hardware estimate by October 25th @akachru-github @andricDu

**Comment by akachru-github** [comment]
WARNING: what follows is a series of janky notes from our first meeting: 

- we will be given openstack tenant from IT, lots of cores
- what about persistent storage hw? we need to buy? we get quoted for it? seph? nfs?
- connectivity, loadbalancer?
-- passes through existing F5, what should it go to? multiple NGINX instances? 
-- Ideally we want them to load balance to NGINX instances we manage.
-- ego / gateway is publicly available
- terraform to codify our infra on top of openstack
- new jenkins instance, just for deployment, no builds
-- using IT LDAP
- Use LDAP for kubernetes
- access to henrich for existing tenant
-  Kafka, vault, ES, needs to be setup
- what does IT want to know in terms of auditing for us?
- IT continuing to do backups? they backup latest release of data for projects in ICGC
-- we have to write the backup scripts
- who holds keys to vault?

next steps:
- SOFTENG: Develop terraform script against existing tenancy. jenkins, vault, kubs, ES setup dry run. make us ready for tenancy nov 1. @akachru-github  to create ticket. 
- IT: give us tenancy even tho we do not have compute
- IT: potential plan B for drives if we are not going to make nov 1
- IT: Vault integration with LDAP?

**Comment by akachru-github** [comment]
MTG notes IT software monthly mtg:

- bad SAS drives have been replaced (yay!)
- 2 of the 4 nodes available this week to us
- move networking to cumulus?
- VM disk configs, local for ES ? Discuss how to make VMs redundant... 

Questions I captured in our last meeting for IT:
1) Can tenancy be provided even though we do not have compute set up yet?
- we should be getting our nodes this week. don't need to do this. 

2) Can IT get Vault integrated with LDAP for us?

3) What are IT's auditing requirements?

4) Load balancer / NGINX questions, network architecture questions
- all of oicr share f5
- ideally we would like to use the f5
- SSL termination FE on f5.

5) Persistent storage for kubernetes, do we need to purchase this?
- Ceph / cinder.  ~ 20GBs
- The load on the api here is new. Let's keep an eye out. 
- by websites and other infra. 
- we will be accommodated for storage, but we will have to pay for it. 
-- suggestion from IT is to have them buy the storage since our cap isn't big enough to make our own purchase. 

- TODO expectations for backups at OICR? Offisite? (atul)
- TODO tenant flavours? (henrich)
- TODO two IPs load balanced for now. what other requirements are there? Floating internal IPS? (henrich)
- TODO DNS names? (Atul) 
- TODO estimation on persistent storage and variant data storage
