### ISSUE TITLE
PLATFORM Infra / Devops May Release

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/roadmap#166]
**Links**
- Network, Monitoring: https://docs.google.com/document/d/1h6a4cJe0X9FmgzWHvbn_e2tqyr2uOKgM5tye2AM1zKk/edit?usp=sharing
- Backups: https://docs.google.com/document/d/1SG9qWWjutr01rYg-bk1Ba1_cnM_g6tMur4WHBmh0_-0/edit?usp=sharing

**Network Security and Config**
- [x] Pod Security enabled.
- [x] Network Policies enabled in QA and DEV
- [x] Ingress Controllers (private and public) setup.
- [x] Once ready, flip all service to public VIP to expose them to the public
- [x] OICR IT Penn Test results: Potential fix by Infrastructure

**Monitoring**
- [x] Endpoint monitoring enabled
- [x] External cluster monitoring enabled
- [x] Dashboards with simple templated metrics enabled and accessible (Grafana, Prometheus, Kibana)

**Backups**
Ability to schedule and manually kick off backups as well as safely restore the following services:
- [x] Ego (Postgres)
- [x] Program Service (Postgres)
- [x] Lectern (Mongo)
- [x] Clinical (Mongo)
- [x] Jenkins configuration
- [x] Kubernetes configuration
- [x] Vault/Consul

**Environment Parity**
- [x] All environments should have the same application versions and configuration. 

Out of scope:

**High Availability**
- [ ] Ego high availability within the cluster
- [ ] Backup and manual restore of Elasticsearch Indices

**Comment by rosibaj** [comment]
@akachru-github do the remaining tasks need to be moved to a new release?

**Comment by akachru-github** [comment]
Yes, this will be disseminated and closed.

**Comment by akachru-github** [comment]
Out of scope issues were removed. Rest fo the tickets are closed. Closing.
