### ISSUE TITLE
RDPC Infra / Devops May Release

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#179]
**Links**
- Network, Monitoring: https://docs.google.com/document/d/1h6a4cJe0X9FmgzWHvbn_e2tqyr2uOKgM5tye2AM1zKk/edit?usp=sharing
- Backups: https://docs.google.com/document/d/1SG9qWWjutr01rYg-bk1Ba1_cnM_g6tMur4WHBmh0_-0/edit?usp=sharing

**Network Security and Config**
- [x] Pod Security enabled.
- [x] Ingress Controllers (private and public) setup.
- [x] Network Policies enabled.

**Monitoring**
- [ ] Endpoint monitoring enabled
- [x] External cluster monitoring enabled (this is done for Collab already using Uptime Robot)
- [ ] Dashboards with simple templated metrics enabled and accessible (Grafana, Prometheus, Kibana)

**Backups**
- [ ] Kafka (filestore)
- [ ] Song (postgres)
- [ ] QC module (undecided storage)
- [x] Kubernetes configuration
- [ ] Jenkins configuration
- [ ] Replication to IT / Isilon for all backups
--------

- [ ] Secure and deployed Canadian RDPC setup with all services deployed 
- [ ] Logging and monitoring
- [ ] Caching in Collab - Github, Quay, Dockerhub

**Comment by rosibaj** [comment]
@akachru-github does this epic need to be separated into to others now?  We are past the may release?

**Comment by akachru-github** [comment]
Yep. In the process of disseminating this and closing it.
