### ISSUE TITLE
Production Setup Tracking

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#225]
We need to have a discussion about our infrastructure.  

#### Services
These need to be duplicated in `dev` & `qa` namespaces in `argo-qa` cluster, and `stage` and `prod` namespaces in `argo` cluster. 
- [ ] Platform [NEEDS DNS UPDATE]
- [ ] Platform Gateway API [NEEDS DNS UPDATE]
- [ ] Ego [NEEDS DNS UPDATE]
- [ ] Ego UI 
- [ ] DACO2Ego
- [ ] Clinical
- [ ] Lectern
- [ ] Program Service (how have we not renamed this yet?!)
- [ ] Documentation site [NEEDS DNS UPDATE]
- [ ] ⚠ Arranger [NOT DONE, NEEDS WORK]
- [ ] ⚠ Maestro [NOT DONE, NEEDS WORK]
- [ ] ⚠ Rollcall [NOT DONE, NEEDS WORK]
- [ ] ⚠ Dashboard Aggregator [NEW, NEEDS WORK]
- [x] Mail Server

#### Stuff
- [ ] ⚠ Kafka [not sure]
- [ ] ⚠ Elasticsearch 
- [ ] ⚠ Kibana?
- [x] vault
#### Services 
These need to be deployed in `rdpc-collab` namespaces, in `rdpc` cluster.
These needs to be deployed in `rdpc-dev` namepace `dev` 
- [ ] ⚠ Score [deploy in progress - CM 23]
- [ ] ⚠ Song  [deploy in progress - CM 23] 
- [ ] ⚠ Song-qc sidecar [NEW, NEEDS WORK] [in progress - CM 23]
- [ ] Kafka [deploy in progress - CM 22] 
- [ ] Elasticsearch [deploy in progress - CM 22] 
- [ ] Workflow Search
- [ ] Workflow Relay
- [ ] Workflow Management
- [ ] Workflow Gateway
- [ ] Workflow UI
- [ ] Working API Docs Service
- [ ] ⚠ Kafka Connector to external Kafka topics  [NEW, NEEDS WORK]  [code in progress - DK-22]
- [ ] ⚠ Ego replicated as a backup (postgres read only slave) 
#### Stuff
- [x] ⚠Collab production bucket for data [in progress - CM 23]
- [ ] ⚠ RDPC jenkins server (simiar to the argo one managing clinical in prod) [in progress - CM 23]
- [ ] ⚠RDPC github repo to store our helm values for prod, and need it to be locked down
- [ ] NFS / PersistentVolume config

**Comment by joneubank** [comment]
Email Services?
