### ISSUE TITLE
Entity Pages: Donor

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#340]
## Expected Outcomes from the Epic
Goal:  to build the Donor page that displays all of the available clinical data for a donor, based on the most current data dictionary. 
Wiki specs: https://wiki.oicr.on.ca/display/icgcargotech/Donor+Entity+Page

- [ ] 1. The title bar has a legend, a link to the clinical data dictionary a button to download the file manifest for this donor and a button to download all available clinical data
- [ ] 2. The donor summary is hooked up
- [ ] 2b. Feature request: We can convert the ICD-10 code (in cancer_type_code) to an actual string. For example, C41.1 codes for Malignant neoplasm: Mandible. So this field would display as Cancer Type: Malignant neoplasm: Mandible (C41.1)
- [ ] 3. The available files matrix is built and hooked up based on what molecular files exist for this donor, with links to the file repository filtered on this donor and type of file. 
- [ ] 4. Clinical timeline is functional, showing all of the files associated to a donor in a chronological time scale. Do not show the tabs if a donor doesn't have, say, a biomarker.
- [ ] 5. The Exposure, Comorbidity and Family history tables are optionally present, if they have been submitted - and hidden if they are not submitted.
- [ ] To Do: discuss a plan to keep this page up to date with any dictionary changes.

![image](https://user-images.githubusercontent.com/18424138/160918105-30db0751-de00-48a8-b4f9-b7f7c771b016.png)
