### ISSUE TITLE
🐛 Add Vault support to lectern helm deployments

### ISSUE THREAD

**Issue by rtisma** [icgc-argo/roadmap#395]
Currently, secrets are exposed since not using k8s secrets engine. In addition, lectern app supports vault, but was not deployed to use vault in any of the environments

This change means:
- [x] updating the values (https://github.com/OICR/argo-infra/issues/177)
- [x] creating, policies, roles and secrets in vault (https://github.com/icgc-argo/roadmap/issues/396)
- [x] update lectern chart with proper RBAC config for k8s (https://github.com/overture-stack/helm-charts/issues/48)
- [x] updating passwords, deploying lectern and smoke testing (https://github.com/icgc-argo/roadmap/issues/397)
- [x] verify deploymnt in platform-dev, platform-qa,  platform-prod
