### ISSUE TITLE
Prep production for Release 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#439]
- [x] **May 29 **  ensure all data is cleared from prod. (https://github.com/icgc-argo/roadmap/issues/408)
- [ ] Initialize a single test project in production. 
- [x] Initialize PACA-CA in prod in prod from legacy migration. (https://github.com/icgc-argo/roadmap/issues/453)
- [x] Initialize OCCAMS-GB (formerly ESAD-UK) in prod from legacy migration. . (https://github.com/icgc-argo/roadmap/issues/453)
- [x] Point Prod Song to Prod Clinical to test prod-to-prod communication [still on private ingress for Song] (note currently its looking at QA Clinical) (https://github.com/icgc-argo/roadmap/issues/459 )
- [x] Ensure workflows can run successfully
- [x] **June 4** Open services to public ingress (https://app.zenhub.com/workspaces/argo-mega-board-all-repos-5c8c8637777e5f767e486217/issues/icgc-argo/roadmap/399) 
- [x] Scan to remove any prod access that is currently allowed that should not be. 
- [x] Add the correct DCC Admin member privileges for 
------- Christina, Dusan, Rosi, Hardeep
- [x] DACO2Ego Verification into prod ego working (https://github.com/icgc-argo/roadmap/issues/455)
- [x] Verify docs site is on latest release dictionary
