### ISSUE TITLE
File Repository Release: June 19th 2020

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#473]
- [x] Project Initialization: https://github.com/icgc-argo/roadmap/issues/460
- [x]  Search Analyzer Update:  (WIP) https://github.com/icgc-argo/platform-ui/issues/1614
- [x] add `submitter_donor_id` to table  https://github.com/icgc-argo/platform-ui/issues/1616  (WIP)
- [x] Reorder facets: https://github.com/icgc-argo/platform-ui/issues/1618   (WIP)
- [x] manifest download bug https://github.com/icgc-argo/platform-api/issues/267  (WIP)
- [x] Index final prod index for release: https://github.com/icgc-argo/roadmap/issues/468  (WIP)
- [x] Make site public (deploy site without feature flags)
-  [x] Release dictionary 1.0.0  (WIP)
- [x] Release Docs site with FIRST release notes and dictionary 1.0.0  (WIP)
https://github.com/icgc-argo/argo-docs/issues/233
- [x] Update home page: https://github.com/icgc-argo/platform-ui/issues/1621   (WIP)
- [x] Update cookie banner: https://github.com/icgc-argo/platform-ui/issues/1624  (WIP)
- [x] Make Song/Score public
- [x]  Homepage announcement: https://github.com/icgc-argo/platform-ui/issues/1641
- [x] Communications Post from Christoper  (WIP)
