### ISSUE TITLE
Workflow Automation

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#519]
https://wiki.oicr.on.ca/pages/viewpage.action?spaceKey=icgcargotech&title=Worfklow+Graph+Design 

![image](https://user-images.githubusercontent.com/15824252/88303676-4e2e9f00-ccd5-11ea-95f8-93adfaa14937.png)

https://wiki.oicr.on.ca/display/icgcargotech/Mapping+Model+Tee+to+Workflow+Automation 

General Three Month Roadmap
----------------------------------------------------

- [x] An application to host nodes/edges.  
-- https://github.com/icgc-argo/roadmap/issues/522
-- https://github.com/icgc-argo/roadmap/issues/521
- [ ] the rdpc-gateway connected to clinical data so we have the ability to filter on all required entities
- [x] an API to create Workflow Nodes [message schema validation included in this]
- [x] an API to create Workflow Edges [message schema validation included in this]
- [ ]  Basic reporting on numbers in queues [ex. align.start]
- [ ] start and stop pipelines, maybe disable edges without deleting them?
- [ ] a retry mechanism for failed jobs
- [ ] Integration of application level tokens and k8s secretes that dusan is working on

The expectation at the end of this roadmap chunk is that:
-  I can publish 2 sequencing experiments (T/N) for one clinically complete donor, and see it go through alignment and vc with no manual input.
- I can see how many wfs are scheduled (capacity) in at least a light version

Work after that ( as a loose idea) would be:
- Ability to prioritize queues [know which projects/donors are in queue, and bump up/down as needed)
- An API to create a pipeline graph [A versioned collection of workflow nodes and edges]
- A UI to show stats/pipeleines/queues
The expectation at the end of this future roadmap chunk is that:
- while the process is automated, i can have some light control over managing which wfs actually get started (edited)
