### ISSUE TITLE
Data Release to File Repository 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#529]
https://wiki.oicr.on.ca/pages/viewpage.action?spaceKey=icgcargotech&title=Data+Release

- [x] **Step 1:** Initialize the the File Service record/tags for all existing files. https://github.com/icgc-argo/files-service/issues/53
-------> has all files tagged with Release state public 
-------> otherwise, new files get OWN_PROGRAM  
- [ ] **Step 2:** Have file service take over publishing file data (without maestro!) https://github.com/icgc-argo/files-service/issues/54
--- Index must include RELEASE_STAGE file. 
--- When we have fs take over, we will replace teh public index (exact same as now)
--- Publish the same current index, with file-service, but now has the release_stage in index. complete backup of this index as well. 
------- At a program level,  PUBLIC will go to PUBLIC index, [OWNPROGRAM,FULL,ASSOCIATE] goes to an EMBARGO index 
2.1 File service needs to be able to responsd to Song publish, unpublish, and suppress.

\>>> **Once this is done, the index will have release stage.  This unblocks:**
> - the aggregation facet can be released
> - the download proxy feature for song/score can be released 
> - the download button from the platform from file repo/file page can go forward. 

- [ ] **Step 3:**  Modify the mapping to add clinical data to the mapping(s).  Put fake data in QA to develop against. 
- confirm the shape of the mapping with all current fields: https://github.com/icgc-argo/argo-metadata-schemas/issues/43
- create a set of fake data to work with:  https://github.com/icgc-argo/roadmap/issues/741

\>>> **Once this is done, the index will have release stage.  This unblocks:**
> - File Entity Page development 
> - Donor Entity Page Development 

- [ ] **Step 4:** Work on FS Release Endpoints. Start a new release, give release summary, confirm/publish release. https://github.com/icgc-argo/files-service/issues/55  

- [ ] **Step 5:** Manual task: Analysisid (and file list) from Bioinfo/Rosi to Jon to set to QUEUED FOR RELEASE file tag in file service. 

\>>>  **Once this is done, the index will have release stage.  This unblocks:**
> Mutect 2 release 

- [ ] **Step 6:** Add clinical indexing to the file_centric index. 
-- get data ergonomically out of clinical per program/per donor: https://github.com/icgc-argo/argo-clinical/issues/442
-- index the data out of clinical into the indices.  https://github.com/icgc-argo/files-service/issues/56,
-- add new data to to platform-api schema: https://github.com/icgc-argo/platform-api/issues/380 

- [ ] **Step 7:** Event based clinical data updates [only for embargo'd data] 
-- clinical sends events when a program has new data submitted:  https://github.com/icgc-argo/files-service/issues/25, https://github.com/icgc-argo/argo-clinical/issues/601
-- file-service listen to events from kafka from clinical to update embargo indices with latest clinical data.  Don't update public donor data. 

- [ ] **Step 8:** Other needed Actions
-- Event synthesizer: https://github.com/icgc-argo/roadmap/issues/586 
-- re- index when tags updated:  https://github.com/icgc-argo/files-service/issues/22
-- re-index when new repository added: https://github.com/icgc-argo/files-service/issues/24
