### ISSUE TITLE
Song Kafka Messaging Enhancements for Platform Indexing

### ISSUE THREAD

**Issue by andricDu** [icgc-argo/roadmap#593]
# Description
We want to send the analysis json as part of the song kafka message that song produces as state changes happen to an analysis.

# Motivation
Currently the analysis is not part of the kafka message and as such, maestro or any other service watching these events that needs information from the analysis (workflow-graph), need to make requests to song to get the information they need. This eliminates some of the benefits of being event driven by adding extra unnecessary calls

# Work

## Song
- [x] Song adds Analysis JSON to Kafka Message. This should be backwards compatible as it is adding a new field and not modifying any of the existing.  (**RDPC**)

## Indexing
- [ ] Maestro will use new Analysis JSON included in message to perform upserts rather than reaching out to song. (**RDPC**)
- [ ] File Orchestrator/Manager (**Platform**)

## Kafka Infrastructure
- [ ] Kafka Retention in Platform so we can replay events (**Platform**)
- [ ] Kafka Compaction in Platform so that (to an approximation) kafka only contains the latest state of an analysis making reindex much easier and faster. (**Platform**)
- [ ] Kafka Compaction in RDCP --\\-- (**RDPC**)
