### ISSUE TITLE
backup-psql: Migrate from Dockerhub to Github Packages

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/roadmap#614]
### Tasks
- [x] Push/upload image to github registry
- [x] Update psql-backup helm chart to use new image location by default
- [x] Update values and re-deploy all helm chart releases based on psql-backup helm chart

### Inventory for all psql-backup based helm chart releases to re-deploy:
- [x] RDPC DEV/QA
- intermediate-song-rdpc-dev-psql-backup
- intermediate-song-rdpc-qa-psql-backup 
- song-rdpc-dev-psql-backup
- song-rdpc-qa-psql-backup
- submission-song-rdpc-dev-psql-backup
- submission-song-rdpc-qa-psql-backup
- [x] RDPC PROD
- intermediate-song-rdpc-prod-psql-backup
- song-rdpc-prod-psql-backup
- submission-song-rdpc-prod-psql-backup
- [x] ARGO DEV/QA
- ego-argo-dev-backup
- ego-argo-qa-backup
- program-service-backup-dev
- program-service-backup-qa
- [x] ARGO PROD
- ego-argo-prod-backup
- ego-argo-staging-backup
- program-service-argo-prod-backup
- program-service-argo-staging-backup
