### ISSUE TITLE
backup-mongo: Migrate from Dockerhub to Github Packages

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/roadmap#616]
### Tasks
- [x] Configure automation for building and pushing docker image to ghcr.io registry
- [x] Push/upload image to github registry
- [x] Update helm chart to use new image location by default
- [x] Update values and re-deploy all helm chart releases based on the helm chart

Inventory for helm chart releases to be re-deployed:
- [x] clinical-mongo-backup - ARGO DEV
- [x] clinical-mongo-backup - ARGO QA
- [x] clinical-mongo-backup - ARGO STAGNING
- [x] clinical-mongo-backup - ARGO PROD
