### ISSUE TITLE
kafka-connect: Migrate from Dockerhub to Github Packages

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/roadmap#618]
### Tasks
- [x] Configure automation for building and pushing docker image to ghcr.io registry
- [x] Push/upload image to github registry
- [x] Update helm chart to use new image location by default
- [x] Update values and re-deploy all helm chart releases based on the helm chart

Inventory for helm chart releases to be re-deployed:
- [x] kafka-connect-rdpc-dev - RDPC DEV
- [x] kafka-connect-rdpc-QA - RDPC QA
- [x] kafka-connect-rdpc-prod - RDPC PROD

**Comment by akachru-github** [comment]
Repurposed to kafka-connect from mongo.
