### ISSUE TITLE
consul-backup: Migrate from Dockerhub to Github Packages

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/roadmap#619]
### Tasks
- [x] Add automation (Jenkinsfile) to push newly built docker images to ghcr.io registry
- [x] Push/upload image to github registry and make it public
- [x] Update helm chart to use new image location by default
- [x] Update values and re-deploy all helm chart releases based on the helm chart

### Inventory for helm chart releases to be re-deployed and validated:
- [x] ARGO Platform DEV/QA
- [x] ARGO Platform STAGING/PROD
### New deployments
- [x] RDPC DEV/QA
- [x] RDPC PROD
