### ISSUE TITLE
Molecular Data Release - Prep for Soft-Launch

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#660]
https://wiki.oicr.on.ca/display/icgcargotech/Molecular+Data+Release 

**Scope of the Beta Test:**
Allow MUTO-INTL to submit data files to the Submission Song.  10 donors with T/N. 

At a high level this means they should be able to:
1. Register their samples successfully. 
1. Use the client-side tool to validate data.
1. Successfully submit data to `submission-song` for their program. 
1. Test the pipeline from align to mutect and make sure with external data we have no issues. 

Start Date: *December 9th* 

**Software Needs**: 
- [x] Application to Application token changes 
- ~Ego work: https://github.com/overture-stack/ego/issues/467~
- ~RDPC Updates: https://github.com/icgc-argo/roadmap/issues/504~
- [ ] platform to rdpc authentication thru aggregator: https://github.com/icgc-argo/donor-submission-aggregator/issues/98
- [x] Config application-to-application token for 10 days: https://github.com/icgc-argo/roadmap/issues/662
- [x] 🚧Workflow Authorization Updates [Enacting the token updates]: https://github.com/icgc-argo/workflow-roadmap/issues/33 
- [x] 🚧Timestamps in Song: https://github.com/overture-stack/SONG/issues/678 
- [x] ⚠️Maestro indexing issues: https://github.com/icgc-argo/workflow-roadmap/issues/73
- [x] 🚧Backup Songs  https://github.com/overture-stack/SONG/issues/628 
- [x] Replication of back from collab to cumulous https://github.com/icgc-argo/roadmap/issues/383
- [x] Update Song/Score ingress for submission song to be public  https://github.com/icgc-argo/roadmap/issues/661
- [x] Verify feature-flag/deploy of rev-proxy to a single download url to got with #661 above with Minh/Henro
 
**Bioinfo Needs**
- [x] Remove tumour restrictions on 4 fields https://github.com/icgc-argo/argo-dictionary/issues/214
- [x] Create production program in `platform`, `submission-song` and `rdpc-song`.
- [x] Verify latest schema updates on all production Song's
- [x] Test Bioinfo client side tools
- [x] Release QA from Bioinfo tools: https://github.com/icgc-argo/seq-tools/issues/67
