### ISSUE TITLE
DACO Application - MVP/Release 1

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#764]
Timelines:
- First Release early Summer
 Wiki: 
https://wiki.oicr.on.ca/pages/viewpage.action?spaceKey=icgcargotech&title=Data+Access+Control

Features to Implement 

- [x] Informative user experience upfront with landing page, access to policies and help guides to ensure the application process is transparent from the start.
- [x] Google authenticated login.
- [x] Helpful applicant dashboard that communicates the status of all open applications as well as the applicant's status for access to controlled data.
- [x] Intuitive and simplified application form with extensive validation and dynamic progress tracking.
- [x] Ability to download a pdf of the application that reflects its state at any point in time.
- [x] Clear instructions and links for the applicant to contact the DACO office through the ICGC ARGO help desk.
- [x] Ability for the applicant to upload the signed pdf to be submitted to the DACO office.
- [x] Email notification feature that sends out the relevant emails to the applicant, collaborators, and DACO administrators when triggered by certain system events.
- [x] Robust interface for DACO administrators to access all applications, see the status of them, and filter to find specify applications.
- [x] Ability for DACO administrators to review, approve, reject or reopen an application for revisions. These features will allow DACO administrators to send custom reasons for these actions to be emailed to an applicant for assistance the application process.  
- [x] Ability for DACO administrators to edit, revoke access, and reopen an application.
- [x] Ability for an applicant to close an application at any point in the application life cycle and open as many application as they wish.
- [x] Feature that locks the application for editing after approval, but allows the applicant to add or remove collaborators at any point within the access year.
- [x] Feature that ensures all access for a project team is revoked whenever an application is closed within the access year.
- [x] Mechanisms that securely updates the relevant lists for data access with the correct applicant and collaborator google email addresses.
- [x] Secure communication of approved accounts to EGA for access to ICGC2-5K raw data hosted in EGA repository.

Work Breakdown: 

### Track 1 
EPIC 1 - Site scaffolding, Login/permissions, homepage, DACO admin dashboard [Ann]
EPIC 2 - Admin Dashboard Data Hookups [Bashar BE + Ann]

### Track 2
EPIC 3 - Applicant dashboard, Application form [Justin + Ciaran]
EPIC 4 - Application Form Data Hookup: Validation, Status Icons (progress bar + tabs), Sign and Submit, [Bashar BE + Justin + Ciaran]

### Track 3 (assigned after completion above) 
EPIC 5 - Admin Approval Flow, Approved Application state, Editable tabs for DACO Admin, Adding/Removing collaborators post approval
EPIC 6 - Rejection, Close 
EPIC 7 - Changes Requested
EPIC 8 - PDF Download
EPIC 9 - Email and Toast Notifications

### Track 4 
EPIC 10 - Approved Users List Integrations: Platform + EGA 

### Tables for future
Application Renewal

**Comment by kcullion** [comment]
DACO MVP launch was a success on May 16! closing this epic 
@blabadi
