### ISSUE TITLE
EPIC: Submitted Data Section for Programs

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/roadmap#890]
## Goals
Currently a clinical data submitter cannot see what data they have already submitted for their donors and what is left to reach 100% clinical completion. It is also very confusing when donors become invalid for a program, because of dictionary changes. Program members just see an error banner with an invalid icon in the donor table (in a confusing spot) and are not told what to fix. This feature will allow data submitters to see the status of the clinical data that has been submitted for each donor and what to fix when they become invalid.

Wiki specs: https://wiki.oicr.on.ca/display/icgcargotech/Submitted+Clinical+Section+with+Invalid+Donors

### Expected Outcomes for Submitted Data section
- [ ] 1. A submitter can see what clinical data they have submitted as of date (in the same format as they would in the clinical submission section). The file types that don't have any data submitted for them are disabled in the list of tabs.
- [ ] 2. A submitter can see what files they are missing to reach core completion.
- [ ] 3. A submitter can filter the submitted data with some predetermined quick filters
- [ ] 4. A submitter can search for a single donor to load into this submitted data section
- [ ] 5. A submitter can filter by a list of donors to load into the submitted data section
- [ ] 6. A submitter can download all clinical data for the donors that are loaded in this section - or can download by individual file type.
- [ ] 7. Improvements for communicating invalid donors (when data dictionary is updated) in an aggregated error banner with ability to download the details in an error log. 
- [ ] 8. Sorting this view first by any invalid donors (showing the highlighted fields that are invalid) and then sorted by donors that are clinically incomplete (at the top).
- [ ] The no data state for the donors that just have samples registered (donor tab).

![image](https://user-images.githubusercontent.com/18424138/159542266-dc9c2188-dc67-474b-953c-e81403a4117b.png)

### Additions to the donor dashboard table
- [ ] 1. Improvements to donor dashboard table for performing actions (view submitted data and download clinical data) on a bulk set of selected donors. (NICE-TO-HAVE if there's time)
- [ ] 2. Addition of an "Alerts" column (and filter) to show the donors that require updated clinical data (instead of the alert in the released files column)
- [ ] 3. Additions of alert metric that show in the legend (just `requires updated clinical for now`)
- [ ] 4. Quick links for donor id to load that donor's submitted data within this new section. The alerts will link to the first tab for that donor that has the invalid errors).
![image](https://user-images.githubusercontent.com/18424138/159545484-2562dd42-17f5-4ed0-918a-ea9cfc7b2abb.png)

**Comment by b-f-chan** [comment]
Look at pulling clinical data currently submitted and using it to create a test program for this epic/feature (@kcullion, @hknahal)
