### ISSUE TITLE
Vault Integration 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/roadmap#90]
Applications secrets need to be securely manages so that they are not released on code or accessible. We  need to complete integration of all application secrets with Vault.

**Update Services to read from Vault:**
- [x] Ego - https://github.com/icgc-argo/argo-platform/issues/381
- [x] Program Service - https://github.com/icgc-argo/program-service/issues/172
- [x] Maestro- https://github.com/icgc-argo/argo-platform/issues/384 
- [x] Clinical Submission - https://github.com/icgc-argo/argo-clinical/issues/56
- [x] Lectern 

Review these to see if needed: 
- [ ] Song + Score -https://github.com/icgc-argo/platform-ui/issues/382

**Comment by blabadi** [comment]
after discussion with @andricDu we do want to integrate vault with song and score, it should be an straight forward task based on how easy it was to integrate with ego
1- add dependency to each project
2- add proper configuration in helm 
3- add the secrets for vault in Dev and QA
4- delete and reinstall the charts to confirm they pickup things correctly in Dev & QA

**Comment by blabadi** [comment]
a final step to verify that services work without *ANY* secrets being exposed in the values files of any service would be a good sign off for this to be marked as completed, and we should be able to remove the `--reuse-values` flag from our deployment script

**Comment by blabadi** [comment]
the UI and the gateway currently don't have any secrets, no vault integration needed there as of now

**Comment by andricDu** [comment]
Just to follow up because I know I flipped on this, the integration should be really simple, and it is not something that needs to be used by end users. 

There is no code required for this to be implemented. 

And I agree with @blabadi , having no secrets being exposed in values or to Jenkins would go a long way in elevating the security of the whole infrastructure.
