### ISSUE TITLE
Upgrade Elasticsearch to New Hardware for ICGC25K

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/roadmap#914]
Current ES was built on actual physical services in Mars building, security risks are present and need to be addressed. 

Goal is to rebuild ES cluster in a new environment like Openstack.

2 stages:
-> test cluster
-> get portals to connect to the new cluster. 

@joneubank @b-f-chan Break it down into small tickets. 

*** **Sub-Tasks for this Ticket** ***

As discussed and agreed with @joneubank, we won't create separate tickets, but track sub-tasks for this work here:

- [ ] (1) Investigate and confirm we still have the backup files required to run the process to rebuild the ES index
- [ ] (2) If the files exist, ask IT to spin up a test cluster on Cumulus and use it to validate the rebuild / re-index process
- [ ] (3) If the test rebuild works, ask IT to then spin up a production ready cluster on Cumulus, and we will do the real rebuild / re-index process on prod
- [ ] (4) Index the missing Azure data into the file repository (the Azure data is newer and was not indexed into the repo)
- [ ] (5) Point the production ICGC25K portal to the newly-indexed prod cluster (should be a setting/config that IT updates then restarts on a a Java app)
- [ ] (6) Notify IT that the rebuild is complete and the upgrade to new hardware for ES is done, they can then tear down the old existing prod cluster

**Comment by Buwujiu** [comment]
no updates, we’re not focusing on icgc hardware for the moment.

**Comment by joneubank** [comment]
ICGC25k is now retired.
