### ISSUE TITLE
Deploy Clinical Service to Cumulus RDPC

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/roadmap#968]
## Goal
No code change. Deploy the platform clinical service to RDPC cluster. 
Devop tasks: Add helm chart, network policy, terraform. 
Also deploy DBs:
- Clincial DB
- RXNorm DB 
## Exit Criteria
- Clinical service is up and running in RDPC dev and QA. 

### General:
- [x] Setup RBACs to allow Ummulkiram access to RDPC DEV Cumulus cluster
- [ ] Migrate clinical docker build pipeline to new Jenkins instance in RDPC DEV Cumulus
### Task specific
- [x] Add DNS entries for clinical app
- [x] Request IT to add SANs entries for clinical app ingress encryption
- [x] Update tf code to add following helm releases in respective tf projects:
  - clinical
  - clinical-db
  - clinical
- [x] Add postrenderer instructions
  - [x] Update existing kustomize instructions
  - [x] Add netpol instructions 
- [x] Update and add values to tf projects
- [x] Add deployment secrets for helm
- [x] Add runtime secrets for clinical service
- [x] Deploy helm chart all 3 helm charts
  - [x] clinical
  - [x] clinical-db
  - [x] rxnormdb
- [x] Populate rxnormdb as detailed here:
  - https://github.com/icgc-argo/argo-clinical#importing-rxnorm
  - https://jenkins.qa.cancercollaboratory.org/job/ARGO/job/devops/job/rxnorm-import/

**Comment by bhavikbhagat93** [comment]
This ticket can be done after #1015
